@HostAddress = http://localhost:5109/api/roles

### Get all roles
GET {{HostAddress}}?page=1&pageSize=10

### Get role by id
GET {{HostAddress}}/019cfa36-69d8-72c5-8d00-431a7044626c

### Create role
POST {{HostAddress}}
Content-Type: application/json

{
  "name": "Administrator",
  "permissionIds": [
    "019cfa36-69d8-72c5-8d00-431a7044626d"
  ]
}

### Update role
PUT {{HostAddress}}/019cfa36-69d8-72c5-8d00-431a7044626c
Content-Type: application/json

{
  "name": "Updated Administrator",
  "permissionIds": [
    "019cfa36-69d8-72c5-8d00-431a7044626d",
    "019cfa36-69d8-72c5-8d00-431a7044626e"
  ]
}

### Delete role
DELETE {{HostAddress}}/019d41af-378c-78c5-b2ba-093f10ab3a4d